language: objective-c
osx_image: xcode8

install: 
  - git clone https://github.com/Electrode-iOS/ELRouter.git ../ELRouter
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
  - git clone https://github.com/Electrode-iOS/ELDispatch.git ../ELDispatch
  - git clone https://github.com/Electrode-iOS/ELLog.git ../ELLog

script:
   - xcodebuild -scheme ELMaestro -sdk iphonesimulator test -destination 'OS=10.0,name=iPhone 7 Plus' CODE_SIGNING_REQUIRED=NO
