language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/WalmartLabs/ELRouter.git ../ELRouter
  - git clone https://github.com/WalmartLabs/Excalibur.git ../Excalibur
  - git clone https://github.com/WalmartLabs/KillerRabbit.git ../KillerRabbit
  - git clone https://github.com/WalmartLabs/Shrubbery.git ../Shrubbery

script:
   - xctool -project ELMaestro.xcodeproj -scheme ELMaestro -sdk iphonesimulator build test
