language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/TheHolyGrail/Maynard.git ../Maynard
  - git clone https://github.com/TheHolyGrail/Excalibur.git ../Excalibur
script:
   - xctool -project THGSupervisor.xcodeproj -scheme THGSupervisor -sdk iphonesimulator build test
